version: '3.4'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - api
      - frontend
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./front:/var/www/front:cached
      - ./api:/var/www/api:cached
      - .docker-compose/nginx/cojedzie.conf:/etc/nginx/conf.d/cojedzie.conf

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["php-fpm"]
    environment:
      - APP_MODE=debug
      - CORS_ALLOW_ORIGIN=*
    env_file:
      - .docker-compose/api/.env
    volumes:
      - ./api:/var/www
      - .docker-compose/api/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  worker:
    image: cojedzie/worker:latest
    env_file:
      - .docker-compose/api/.env
      - api/.env.local
    volumes:
      - ./api:/var/www
      - ./build/worker/supervisord-init.sh:/var/www/bin/supervisord-init.sh
      - .docker-compose/api/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  cron:
    image: cojedzie/cron:latest
    env_file:
      - .docker-compose/api/.env
      - api/.env.local
    volumes:
      - ./api:/var/www
      - .docker-compose/api/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  frontend:
    image: node:16
    working_dir: /app
    environment:
      - COJEDZIE_MODE=development
      - COJEDZIE_API=http://nginx/api
      - COJEDZIE_API_HUB=http://cojedzie.localhost
      - COJEDZIE_MAPTILER_KEY
    volumes:
      - ./front:/app
    ports:
      - '3001:3001' # required for vite HMR
    command: ["node", "build/server.js"]

  storybook:
    image: node:16
    working_dir: /app
    environment:
      - STORYBOOK_BASE_HREF=/storybook/
      - APP_MAPTILER_KEY
      - APP_API_BASE_URL=http://cojedzie.localhost
    volumes:
      - ./front:/app
    ports:
      - 6006:6006
    command: ["yarn", "storybook"]

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cojedzie
      - POSTGRES_PASSWORD=cojedzie
      - POSTGRES_DB=cojedzie
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mysql:
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=cojedzie
      - MYSQL_PASSWORD=cojedzie
      - MYSQL_DATABASE=cojedzie
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      USE_FORWARDED_HEADERS: 1
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  mysql_data:
