services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    ports:
      - 5601:5601
    depends_on: ["elasticsearch"]

volumes:
  es_data: ~
