version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./front:/var/www/front:cached
      - ./api:/var/www/api:cached
      - .docker-compose/nginx/cojedzie-rr.conf:/etc/nginx/conf.d/cojedzie-rr.conf

  api:
    build:
      context: ./api
      dockerfile: rr.Dockerfile
    env_file:
      - .docker-compose/api/.env
      - api/.env.local
    environment:
      - APP_MODE=${APP_MODE:-debug}
      - CORS_ALLOW_ORIGIN=*
      - TRUSTED_PROXIES=172.0.0.0/8
    ports:
      - 8888:8080
    volumes:
      - ./api:/var/www:cached
      - .docker-compose/api/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    command: ["rr", "serve", "-c", ".rr.yaml"]

  frontend:
    image: node:16
    working_dir: /app
    environment:
      - COJEDZIE_MODE=development
      - COJEDZIE_API=http://nginx/api
      - COJEDZIE_API_HUB=http://cojedzie.localhost
      - COJEDZIE_MAPTILER_KEY
    volumes:
      - ./front:/app
    ports:
      - '3001:3001' # required for vite HMR
    command: ["node", "build/server.js"]

  mysql:
    image: mariadb:10.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=cojedzie
      - MYSQL_PASSWORD=cojedzie
      - MYSQL_DATABASE=cojedzie
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      USE_FORWARDED_HEADERS: 1
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  mysql_data:
