version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./front:/var/www/front:cached
      - ./api:/var/www/api:cached
      - ./docker/nginx/czydojade:/etc/nginx/conf.d/czydojade.conf

  api:
    build: ./api
    env_file:
      - ./docker/php/.env
    volumes:
      - ./api:/var/www:cached
      - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  blackfire:
    image: blackfire/blackfire
    ports: ["8707"]
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
