parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        url: '%env(resolve:DATABASE_URL)%'
        logging: '%kernel.debug%'
        profiling: '%kernel.debug%'
        types:
            datetime: App\Doctrine\CarbonDateTimeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
