parameters:
  env(APP_EVENT_QUEUE): "doctrine://default"

framework:
  messenger:
    reset_on_message: true

    transports:
      main: '%env(resolve:APP_EVENT_QUEUE)%'
      sync: 'sync://'

    routing:
      App\Message\UpdateDataMessage: main
      App\Message\CheckConnectionMessage: main
