nelmio_api_doc:
  documentation:
    info:
      title: Co Jedzie?
      version: 0.1.0
    components:
      parameters:
        provider:
          in: path
          name: provider
          description: Data provider identificator, e.g. trojmiasto for ZTM Gdańsk.
          required: true
          schema:
            type: string

  areas:
    path_patterns:
      - /api(?!/doc$) # Accepts routes under /api except /api/doc
