when@prod:
  sentry:
    dsn: '%env(SENTRY_DSN)%'

    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
    register_error_handler: false # Disables the ErrorListener, ExceptionListener and FatalErrorListener integrations of the base PHP SDK

    tracing:
      console:
        excluded_commands:
          - messenger:consume
          - schedule:run
          - federation:check

    options:
      release: '%env(COJEDZIE_VERSION)%'
      environment: '%env(resolve:SENTRY_ENVIRONMENT)%'
      traces_sampler: App\Service\SentrySampler
      integrations:
        - 'Sentry\Integration\IgnoreErrorsIntegration'
