#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PHP_FILES_TO_CHECK=$(git status --porcelain | grep -e '^[AM]\(.*\).php$' | grep api/ | cut -c 8- | tr '\n' ' ')
if [ -n "$PHP_FILES_TO_CHECK" ]; then
    echo "? checking backend code style ($(echo "${PHP_FILES_TO_CHECK}" | wc -w) files)"
    docker compose run -T -u "$(id -u)" api vendor/bin/ecs check $PHP_FILES_TO_CHECK
fi

JS_FILES_TO_CHECK=$(git status --porcelain | grep -e '^[AM]\(.*\).[jt]sx\?$' | grep front/ | cut -c 10- | tr '\n' ' ')
if [ -n "${JS_FILES_TO_CHECK}" ]; then
    echo "? checking front code style ($(echo "${JS_FILES_TO_CHECK}" | wc -w) files)"
    docker compose run -T -u "$(id -u)" frontend node_modules/.bin/prettier $JS_FILES_TO_CHECK --check
fi
